apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 011215723218.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:2b6352fec5c211bcdc12c067b36b95d640582a54
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlemusic-service
  labels:
    app: googlemusic
spec:
  type: ClusterIP
  selector:
    app: googlemusic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
